global:
  scrape_interval:     1m
  evaluation_interval: 1m

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  - job_name: 'agora-el-node'
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets: ['agora-el-node:6060']

  - job_name: 'agora-cl-node'
    static_configs:
      - targets: ['agora-cl-node:8080']

  - job_name: 'agora-cl-validator'
    static_configs:
      - targets: ['agora-cl-validator:8081']
