bootstrap-node:
  - enr:-LG4QI8_vI0er1EoA7XEdAP9ttsjoSbUvqnWBaJ63K7yAALTOwnbHU0vmrlTQcoNLOBOFm5SKCQPTYrmkcj719Fv19qGAYSoiEwZh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhDbjznmJc2VjcDI1NmsxoQPumCgHQq0gs4Fa115kSxTBmWP3i8tHO4B9uKIT41ab24N1ZHCCD6A
  - enr:-LG4QFXc1E4BwcD77RIE_QV6d1MxxhcMnMNPX1j9vhL38fpbRveI-2LReI757bNhKObnudUeeghqTHxmwJtTuYp3EwWGAYSoiHlnh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhAMKPfeJc2VjcDI1NmsxoQIGJI37_jKFvUGk-u_Qv7QIfBntjxqKYbo8GOdQHiM9TIN1ZHCCD6A
  - enr:-LG4QPssvOoy1kHU4rZPUSsqVfx--KwJWFZMIDU1IljJvCcvMucF3vlw6LcQRNfbCRkGfK-0mjjda9_E9HsWGMmh2viGAYSoiLfNh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhBKIqqqJc2VjcDI1NmsxoQPhwMASkY3Xs5x--_g1iAfp6YzSHCd3oO3p0nKMU_obJIN1ZHCCD6A
contract-deployment-block: 26049
rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
datadir: /root/chain/cl/
execution-endpoint: /root/chain/el/geth.ipc
