bootstrap-node:
  - enr:-LG4QOpsopTfDkjfw3F0TzojZgEhAE6MEucBoSK9aQN4rqb2UbQiISaDSUb-D8r4_0Tq-qI3k_Ml9PJ9Pv1P7bmiUnuGAZpTSHGrh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhHCvckSJc2VjcDI1NmsxoQNoPya9OPkhmMKtZf1vWCEgrVVzM71hELeHqx7fVsEa-YN1ZHCCD6A
  - enr:-LG4QEek2wtGRSp-mSvgYxhF0gpvNzzQY0j4Gq1sTaKMaeitdWN_KZEPNWK93GXjGt0HwWZs_M-rxKA-vJ5_PjExEZCGAZpTVkp-h2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhHCvckWJc2VjcDI1NmsxoQPcDE26V07if_KF-98AhyNgzo8PHKtKvAyLw5R88gGtOoN1ZHCCD6A
  - enr:-LG4QDCF4drUhljN9ANI74dNBMktWSuUujXzh6VD1B3be8UST5tk8XpLa0xLyiTnU_KTOTrp_3mX4tsB-fgVl9CK2ZKGAZpTSl-bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhHCvckaJc2VjcDI1NmsxoQK8cBkWf8aR7otYb3asdwsqE7hD9DzGgLGQix7jFc3NuIN1ZHCCD6A
contract-deployment-block: 26049
rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
datadir: /root/chain/cl/
execution-endpoint: /root/chain/el/geth.ipc
