bootstrap-node:
  - enr:-LG4QJWBnp0fQdOlno9E7S9BfpHA9RRXzyKpO3YmuMjGwM7iF-ihvE9rSzMFWsdi6bsYzlsrXG_T-ucOYX3snABZMQyGAYRHxrX1h2F0dG5ldHOIAAAAAAAAAACEZXRoMpCPO2lhLxoAAP__________gmlkgnY0gmlwhCzDCeyJc2VjcDI1NmsxoQMTpBSbzkZqJlPv3liorc_c3CzWIBJfLNIpJctzFVcOv4N1ZHCCD6A
  - enr:-LG4QLXNku0q7RRa5c-bh8YApaxHZKXOQfFV6QIe_1p-MNdmCTU2C-o9dNgMRt06hLLIiruhowioq9Icjrx-b4oDLV-GAYRHyWiwh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCPO2lhLxoAAP__________gmlkgnY0gmlwhAMJZBeJc2VjcDI1NmsxoQOtkQt0SU4noZsJddO7QuAU5CSsL7An33S00K_SzNvie4N1ZHCCD6A
  - enr:-LG4QAXWWgAqUh0AKClbRvwT0iQ7EHOSQfzr2-MMw3sbM0_SdZExZlmoTcZnM2KK-P4Q6JlCQTbnjf8HbKmvi7-e2RmGAYRHyn71h2F0dG5ldHOIAAAAAAAAAACEZXRoMpCPO2lhLxoAAP__________gmlkgnY0gmlwhA3XiRyJc2VjcDI1NmsxoQOsb_Mcx646a5FFiLQDPNzpngqMCP8VsiH6vMQJdKrL2IN1ZHCCD6A
contract-deployment-block: 678481
rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
datadir: /root/chain/cl/
execution-endpoint: /root/chain/el/geth.ipc

