#!/bin/sh

mkdir -p ./chain/

if [ ! -d ./chain/el ]; then
  mkdir ./chain/el

  docker run -it \
    -v $(pwd):/agora_root \
    --name el-node --rm \
    bosagora/agora-el-node:agora_v1.10.23 \
    --datadir=/agora_root/chain/el \
    init \
    /agora_root/config/el/genesis.json

fi

docker run -it \
  -v $(pwd):/agora_root \
  -p 30303:30303 -p 30303:30303/udp \
  --name el-node --rm \
  bosagora/agora-el-node:agora_v1.10.23 \
  --config=/agora_root/config/el/config.toml \
  --datadir=/agora_root/chain/el
