bootstrap-node:
  - enr:-LG4QPtNr0B-c2jpXqRdKnojgIyviBmjtId0TPkFatR4qeL1eNcxjQVPN7CsH7ghsrCT9L-c7HYh_2yJjmSWyo6hACGGAYPzMjulh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhDbjznmJc2VjcDI1NmsxoQPumCgHQq0gs4Fa115kSxTBmWP3i8tHO4B9uKIT41ab24N1ZHCCD6A
  - enr:-LG4QGmofQ_0cUVGFNtoPFY8_iz55n51AhKzlXqKAm_KmhLSFJx6rbQLzSMgW51Sg5J33q7z0aSjid_t46uvtxWf3PeGAYPz2jRGh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhAMKPfeJc2VjcDI1NmsxoQIGJI37_jKFvUGk-u_Qv7QIfBntjxqKYbo8GOdQHiM9TIN1ZHCCD6A
  - enr:-LG4QBN8aXw9KEUzcDI5ejyGi582nsZQeZhIF8ZUGcy_NqMmVYaIRjfun1VZvSiltmFHIjV797NiZwVCWczR7pH75cmGAYPz2td5h2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhBKIqqqJc2VjcDI1NmsxoQPhwMASkY3Xs5x--_g1iAfp6YzSHCd3oO3p0nKMU_obJIN1ZHCCD6A
peer:
  - enr:-MK4QLHtstrRNOzIvIaobkKMZET48QoTwscSalzY4EJJHoSqXAbJ1GBavY7qPlw_dteDxavmKmMsUR3Y_6U7ZzeuRZ-GAYPz_gUZh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBegxb8LxsCALYXAAAAAAAAgmlkgnY0gmlwhDbjznmJc2VjcDI1NmsxoQKGjnImbH2lLsv8u5qhCD152LsM6dVFwRt_OQ_CrNwTZIhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
  - enr:-MK4QLHtstrRNOzIvIaobkKMZET48QoTwscSalzY4EJJHoSqXAbJ1GBavY7qPlw_dteDxavmKmMsUR3Y_6U7ZzeuRZ-GAYPz_gUZh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBegxb8LxsCALYXAAAAAAAAgmlkgnY0gmlwhDbjznmJc2VjcDI1NmsxoQKGjnImbH2lLsv8u5qhCD152LsM6dVFwRt_OQ_CrNwTZIhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
  - enr:-MK4QFAWgiCulXF84X9f5eo9UHVE6FCKLlX5oP9udYJfPqDCBvhSWNbGDGDV9KMRf0s9ytePbdG6L8Xp3rOdNQaUjF2GAYPz_3trh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBegxb8LxsCALYXAAAAAAAAgmlkgnY0gmlwhBKIqqqJc2VjcDI1NmsxoQJBs-E6HoLRbo6PLyZnhhnjT4VwXsk7O9wRcbWu5EABg4hzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
contract-deployment-block: 26049
rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
datadir: /root/chain/cl/
execution-endpoint: /root/chain/el/geth.ipc

