version: '3.3'
services:
  agora-el-node:
    container_name: agora-el-node
    image: bosagora/agora-el-node:v2.0.0
    ports:
      - "6060:6060"
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    restart: always
    volumes:
      - ./root:/root
    command:
      --config=/root/config/el/config.toml
      --datadir=/root/chain/el
      --syncmode=full
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=6060
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  agora-cl-node:
    container_name: agora-cl-node
    image: bosagora/agora-cl-node:v2.0.0
    ports:
      - "3500:3500"
      - "4000:4000"
      - "8080:8080"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
      - ./root:/root
    restart: always
    command:
      --chain-config-file=/root/config/cl/chain-config.yaml
      --config-file=/root/config/cl/config.yaml
      --accept-terms-of-use
      --p2p-host-ip=${P2P_HOST_IP}
      --monitoring-port=8080
      --disable-peer-scorer=true
      --checkpoint-sync-url=https://testnet-sync.bosagora.org
      --genesis-beacon-api-url=https://testnet-sync.bosagora.org
    depends_on:
      - agora-el-node
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  agora-cl-validator:
    container_name: agora-cl-validator
    image: bosagora/agora-cl-validator:v2.0.0
    ports:
      - "8081:8081"
    volumes:
      - ./root:/root
    restart: always
    command:
      --chain-config-file=/root/config/cl/chain-config.yaml
      --config-file=/root/config/cl/config.yaml
      --accept-terms-of-use
      --beacon-rpc-gateway-provider=agora-cl-node:3500
      --beacon-rpc-provider=agora-cl-node:4000
      --wallet-dir=/root/wallet
      --proposer-settings-file=/root/config/cl/proposer_config.json
      --wallet-password-file=/root/config/cl/password.txt
      --monitoring-port=8081
    depends_on:
      - agora-el-node
      - agora-cl-node
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
