version: '3.3'
services:
  agora-el-node:
    container_name: agora-el-node
    image: bosagora/agora-el-node:v2.0.0
    ports:
      - "6060:6060"
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    restart: always
    volumes:
      - ./root:/root
    command:
      --config=/root/config/el/config.toml
      --datadir=/root/chain/el
      --syncmode=full
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=6060
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  agora-cl-node:
    container_name: agora-cl-node
    image: bosagora/agora-cl-node:v2.0.1
    ports:
      - "3500:3500"
      - "4000:4000"
      - "8080:8080"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
      - ./root:/root
    restart: always
    command:
      --chain-config-file=/root/config/cl/chain-config.yaml
      --config-file=/root/config/cl/config.yaml
      --accept-terms-of-use
      --p2p-host-ip=${P2P_HOST_IP}
      --monitoring-port=8080
      --disable-peer-scorer=true
      --checkpoint-sync-url=https://sync.mainnet.bosagora.org
      --genesis-beacon-api-url=https://sync.mainnet.bosagora.org
    depends_on:
      - agora-el-node
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  agora-cl-validator:
    container_name: agora-cl-validator
    image: bosagora/agora-cl-validator:v2.0.1
    ports:
      - "8081:8081"
    volumes:
      - ./root:/root
    restart: always
    command:
      --chain-config-file=/root/config/cl/chain-config.yaml
      --config-file=/root/config/cl/config.yaml
      --accept-terms-of-use
      --beacon-rpc-gateway-provider=agora-cl-node:3500
      --beacon-rpc-provider=agora-cl-node:4000
      --wallet-dir=/root/wallet
      --proposer-settings-file=/root/config/cl/proposer_config.json
      --wallet-password-file=/root/config/cl/password.txt
      --monitoring-port=8081
    depends_on:
      - agora-el-node
      - agora-cl-node
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  validator-balance:
    image: bosagora/validator-balance:v1.0.0-5498e4
    container_name: validator-balance
    ports:
      - '7000:7000'
    restart: always
    environment:
      HOST_IP: 0.0.0.0
      HOST_PORT: 7000
      AGORA_SCAN_URL: https://www.agorascan.io
      AGORA_CL_NODE_URL: http://agora-cl-node:3500
      AGORA_CL_VALIDATOR_METRICS_URL: http://agora-cl-validator:8081
    depends_on:
      - agora-el-node
      - agora-cl-node
      - agora-cl-validator

  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - "9100:9100"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus
      - prometheus_data:/prometheus
    restart: always
    command:
      --web.enable-lifecycle
      --config.file=/etc/prometheus/config.yml
    depends_on:
      - agora-el-node
      - agora-cl-node
      - agora-cl-validator
      - validator-balance
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

volumes:
  prometheus_data:
  grafana_data:
