{
 "title": "Agora Chain Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Total Validator Balance (BOA)",
   "type": "stat",
   "description": "Sum of all validator balances.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_total_balance{job=\"validator-balance\"})",
     "legendFormat": "vbal"
    }
   ]
  },
  {
   "title": "Total Earnings (BOA)",
   "type": "stat",
   "description": "Total BOA return on the initial effective stake of active local validators.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_total_balance{job=\"validator-balance\"})-(count(validator_total_balance{job=\"validator-balance\"} > 20000 and validator_statuses{job=\"validator-balance\"} == 3)*40000)"
    }
   ]
  },
  {
   "title": "Total Return",
   "type": "stat",
   "description": "Total percentage return on the initial effective stake of active local validators. Excess deposits will be reflected as earnings.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(validator_total_balance{job=\"validator-balance\"}) - (count(validator_total_balance{job=\"validator-balance\"} > 20000 and validator_statuses{job=\"validator-balance\"} == 3)*40000))/(count(validator_total_balance{job=\"validator-balance\"} > 20000 and validator_statuses{job=\"validator-balance\"} == 3)*40000)  "
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "The number of peers",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"agora-cl-node\"}",
     "legendFormat": "CL"
    },
    {
     "expr": "p2p_peers{job=\"agora-el-node\"}",
     "legendFormat": "EL"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of BOA balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"agora-cl-node\"} / beacon_prev_epoch_active_gwei{job=\"agora-cl-node\"} )"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{job=\"agora-cl-node\"}/32) - beacon_finalized_epoch{job=\"agora-cl-node\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "The percentage of BOA balances expected to attest that are actually attesting.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Participation Rate" }
   ],
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"agora-cl-node\"} / beacon_prev_epoch_active_gwei{job=\"agora-cl-node\"} )",
     "legendFormat": "participation rate"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node-exporter\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node-exporter\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node-exporter\"}) by (cpu)) "
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{job=\"node-exporter\"}) /  count(count(node_cpu_seconds_total{job=\"node-exporter\"}) by (cpu)) * 100 "
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node-exporter\"} * 100) / node_memory_MemTotal_bytes{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "stat",
   "description": "Basic network info",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", device=\"eth0\"}[$__rate_interval])*8 ",
     "legendFormat": "IN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", device=\"eth0\"}[$__rate_interval])*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "BlockNumbers",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "chain_head_block{job=\"agora-el-node\"}",
     "legendFormat": "Current Block"
    },
    {
     "expr": "chain_head_receipt{job=\"agora-el-node\"}",
     "legendFormat": "Received Block"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{job=\"agora-cl-node\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{job=\"agora-cl-node\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"agora-cl-node\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{job=\"agora-cl-node\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{job=\"agora-cl-node\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  {
   "title": "Local Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "BOA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_total_balance{job=\"validator-balance\"}) - sum(validator_total_balance{job=\"validator-balance\"} offset 1h != 0) - (40000 * count(validator_total_balance{job=\"validator-balance\"} > 20000)) + (40000 * count(validator_total_balance{job=\"validator-balance\"} offset 1h > 20000))"
    }
   ]
  },
  {
   "title": "Daily Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "BOA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_total_balance{job=\"validator-balance\"}) - sum(validator_total_balance{job=\"validator-balance\"} offset 1d != 0) - (40000 * count(validator_total_balance{job=\"validator-balance\"} > 20000)) + (40000 * count(validator_total_balance{job=\"validator-balance\"} offset 1d > 20000))"
    }
   ]
  },
  {
   "title": "Weekly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "BOA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_total_balance{job=\"validator-balance\"}) - sum(validator_total_balance{job=\"validator-balance\"} offset 7d != 0) - (40000 * count(validator_total_balance{job=\"validator-balance\"} > 20000)) + (40000 * count(validator_total_balance{job=\"validator-balance\"} offset 7d > 20000))"
    }
   ]
  },
  {
   "title": "Monthly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "BOA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_total_balance{job=\"validator-balance\"}) - sum(validator_total_balance{job=\"validator-balance\"} offset 30d != 0) - (40000 * count(validator_total_balance{job=\"validator-balance\"} > 20000)) + (40000 * count(validator_total_balance{job=\"validator-balance\"} offset 30d > 20000))"
    }
   ]
  },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Active\",job=\"agora-cl-node\"} ",
     "legendFormat": "active"
    },
    {
     "expr": "validator_count{state=\"Slashed\",job=\"agora-cl-node\"} ",
     "legendFormat": "slashed"
    },
    {
     "expr": "validator_count{state=\"Exited\",job=\"agora-cl-node\"} ",
     "legendFormat": "exited"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"agora-cl-node\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"agora-cl-node\"}",
     "legendFormat": "exiting"
    },
    {
     "expr": "validator_count{state=\"Slashing\",job=\"agora-cl-node\"}",
     "legendFormat": "slashing"
    },
    {
     "expr": "validator_count{job=\"agora-cl-node\", state=\"Active\"}",
     "legendFormat": "active validators"
    }
   ]
  },
  {
   "title": "Queue Lengths",
   "type": "stat",
   "description": "Estimated length of time until all pending and exiting validators have cleared the queues.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((validator_count{state=\"Pending\",job=\"agora-cl-node\"}/6)*6.4)",
     "legendFormat": "pending"
    },
    {
     "expr": "((validator_count{state=\"Exiting\",job=\"agora-cl-node\"}/6)*6.4)",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Hourly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_total_balance{job=\"validator-balance\"}) - sum(validator_total_balance{job=\"validator-balance\"} offset 1h != 0) - (40000 * count(validator_total_balance{job=\"validator-balance\"} > 20000)) +\t(40000 * count(validator_total_balance{job=\"validator-balance\"} offset 1h > 20000)))/(40000 * avg_over_time(count(validator_total_balance{job=\"validator-balance\"} > 20000)[1h:]))) * 365 * 24",
     "legendFormat": "annualized hourly return"
    }
   ]
  },
  {
   "title": "Daily Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_total_balance{job=\"validator-balance\"}) - sum(validator_total_balance{job=\"validator-balance\"} offset 1d != 0) - (40000 * count(validator_total_balance{job=\"validator-balance\"} > 20000)) +\t(40000 * count(validator_total_balance{job=\"validator-balance\"} offset 1d > 20000)))/(40000 * avg_over_time(count(validator_total_balance{job=\"validator-balance\"} > 20000)[1d:]))) * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Weekly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_total_balance{job=\"validator-balance\"}) - sum(validator_total_balance{job=\"validator-balance\"} offset 7d != 0) - (40000 * count(validator_total_balance{job=\"validator-balance\"} > 20000)) +\t(40000 * count(validator_total_balance{job=\"validator-balance\"} offset 7d > 20000)))/(40000 * avg_over_time(count(validator_total_balance{job=\"validator-balance\"} > 20000)[7d:]))) * (365/7)",
     "legendFormat": "annualized weekly return"
    }
   ]
  },
  {
   "title": "Monthly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_total_balance{job=\"validator-balance\"}) - sum(validator_total_balance{job=\"validator-balance\"} offset 30d != 0) - (40000 * count(validator_total_balance{job=\"validator-balance\"} > 20000)) +\t(40000 * count(validator_total_balance{job=\"validator-balance\"} offset 30d > 20000)))/(40000 * avg_over_time(count(validator_total_balance{job=\"validator-balance\"} > 20000)[30d:]))) * (365/30)",
     "legendFormat": "annualized monthly return"
    }
   ]
  },
  {
   "title": "Avg. Balance",
   "type": "stat",
   "description": "Average validator balance across the network",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\",job=\"agora-cl-node\"} / validator_count{state=\"Active\",job=\"agora-cl-node\"} / 1000000000",
     "legendFormat": "eth"
    }
   ]
  },
  {
   "title": "Validator Queues",
   "type": "stat",
   "description": "Current number of pending and exiting validators",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"agora-cl-node\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"agora-cl-node\"}",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Validator Process Stats",
   "type": "table-old",
   "description": "validator stats by public key over the lifetime of the validator process ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_statuses{job=\"validator-balance\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_total_balance{job=\"validator-balance\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") ",
     "legendFormat": "balance"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_proposals{job=\"agora-cl-validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations{job=\"agora-cl-validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_aggregations{job=\"agora-cl-validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_attestations{job=\"agora-cl-validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_aggregations{job=\"agora-cl-validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_inactivity_score{job=\"agora-cl-validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    }
   ]
  },
  {
   "title": "Client Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "EL Peers",
   "type": "graph",
   "description": "The number of peers to which the Agora execution chain is connected",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "p2p_peers{job=\"agora-el-node\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "CL Peers",
   "type": "graph",
   "description": "The number of peers to which the Agora consensus chain is connected",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"agora-cl-node\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Process Uptimes",
   "type": "stat",
   "description": "The length of time the agora consensus chain and validator processes have been running.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"agora-cl-node\"})/3600",
     "legendFormat": "node"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"agora-cl-validator\"})/3600",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Slots behind",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "Slots behind"
    }
   ]
  },
  {
   "title": "CL-Node Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"agora-cl-node\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"agora-cl-node\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"agora-cl-validator\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"agora-cl-validator\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "RAM Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes  - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes",
     "legendFormat": "RAM Cache + Buffer"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "RAM Free" },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\"}[$__rate_interval])*8 ",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}